services:
  genesis:
    build: .
    container_name: genesis_argo_container
    gpus: all
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    ipc: host
    command: sleep infinity
